// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-tdWlXC40DmHhUMvVwRAq3UAzrsxJ0wI',
    appId: '1:946495234586:web:e7a046237092b8068ee7a3',
    messagingSenderId: '946495234586',
    projectId: 'apptask-aad1b',
    authDomain: 'apptask-aad1b.firebaseapp.com',
    storageBucket: 'apptask-aad1b.firebasestorage.app',
    measurementId: 'G-FZMJHJ6T0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgPbllt5QWsO-DoaYLG57mdzJDIXxN7tg',
    appId: '1:946495234586:android:e4ed0f438c119e528ee7a3',
    messagingSenderId: '946495234586',
    projectId: 'apptask-aad1b',
    storageBucket: 'apptask-aad1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr8FOQvkCgu7CLru6kwEbiOBYzcl1Qsb4',
    appId: '1:946495234586:ios:bd0d89e8815c0e5b8ee7a3',
    messagingSenderId: '946495234586',
    projectId: 'apptask-aad1b',
    storageBucket: 'apptask-aad1b.firebasestorage.app',
    iosBundleId: 'com.app.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr8FOQvkCgu7CLru6kwEbiOBYzcl1Qsb4',
    appId: '1:946495234586:ios:bd0d89e8815c0e5b8ee7a3',
    messagingSenderId: '946495234586',
    projectId: 'apptask-aad1b',
    storageBucket: 'apptask-aad1b.firebasestorage.app',
    iosBundleId: 'com.app.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-tdWlXC40DmHhUMvVwRAq3UAzrsxJ0wI',
    appId: '1:946495234586:web:bc27eaee7b7fd7078ee7a3',
    messagingSenderId: '946495234586',
    projectId: 'apptask-aad1b',
    authDomain: 'apptask-aad1b.firebaseapp.com',
    storageBucket: 'apptask-aad1b.firebasestorage.app',
    measurementId: 'G-9WL05KJN0Y',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA-tdWlXC40DmHhUMvVwRAq3UAzrsxJ0wI',
    appId: '1:946495234586:web:f119b56a648d1f0e8ee7a3',
    messagingSenderId: '946495234586',
    projectId: 'apptask-aad1b',
    authDomain: 'apptask-aad1b.firebaseapp.com',
    storageBucket: 'apptask-aad1b.firebasestorage.app',
    measurementId: 'G-GGSY5QXVFY',
  );
}
